#! /bin/sh

sxhkd &
#nm-applet &
compton &
mpd &
#/opt/pia/run.sh --startup &
/opt/urserver/urserver-start --no-manager --no-notify &
unclutter &
xrandr --output DisplayPort-0 --auto & xrandr --output HDMI-A-1 --off &
feh --bg-fill /home/cabe/.wallpaper.jpg &
#/home/cabe/.config/polybar/launch.sh &

bspc monitor -d terminal web media games draw virtual
# bspc monitor HDMI-0 -d  projector

# MUST be true otherwise the removed monitor will prevent moving the last
# desktop to primary monitor
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# setup monitors
#. /home/cabe/.config/bspwm/multimonitor.sh

source "${HOME}/.cache/squash/colors"
bspc config normal_border_color "${BSPWM_NORMAL}"
bspc config focused_border_color "${BSPWM_FOCUSED}"

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a virt-manager desktop=^6
bspc rule -a Steam desktop=^4

bspc config super mod4
bspc config pointer_action1 move
bspc config click_to_focus true
