#! /bin/sh

sxhkd &
nm-applet &
#compton --inactive-dim 0.3 --focus-exclude '_NET_WM_NAME@:s = "rofi"' &
compton &
/opt/urserver/urserver-start &
unclutter &
/home/cabe/.config/polybar/launch.sh &
xrandr --output DP-2 --mode 2560x1080 -r 75 &
feh --bg-fill /home/cabe/.wallpaper.jpg &

bspc monitor -d terminal web media games draw virtual
# bspc monitor HDMI-0 -d  projector

# monitor 
# MUST be true otherwise the removed monitor will prevent moving the last
# desktop to primary monitor
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


# setup monitors
. /home/cabe/.config/bspwm/multimonitor.sh

source "${HOME}/.cache/squash/colors"
bspc config normal_border_color "${BSPWM_NORMAL}"
bspc config focused_border_color "${BSPWM_FOCUSED}"

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a virt-manager desktop=^6 
bspc rule -a Steam desktop=^4 follow=on
bspc rule -a Media_Center_24 state=floating
bspc rule -a "JRiver Display Class" state=fullscreen


bspc config super mod4
bspc config pointer_action1 move
bspc config click_to_focus true

# autostart programs

# manage wallpaper
#if [ -x /usr/bin/feh ]; then
#	if[ -f $HOME/.wallpaper.jpg ]; then
#		feh --bg-fill /home/cabe/.wallpaper.jpg
#	else
#		feh --bg-fill /home/cabe/.wall_gradient.png
#	fi
#fi

# display compositor
#if [ -x /usr/bin/compton ]; then
#	compton -b --inactive-dim 0.3 --focus-exclude '_NET_WM_NAME@:s = "rofi"' &
#fi
#
wait
